mariadb:
  debug: true

  # general cluster parameters
  cluster:
    id: null                                     # e.g. "1"
    topology: masterslave                        # possible values "masterslave", "standalone", "galera", "columnstore", "columnstore-standalone" 
    labels: null                                 # custom labels to be added to the mariadb service, e.g. for discovery   
    annotations: null                            # custom annotations to be added to each pod in the cluster
    monitoring:
      mode: "global"                             # global for integration with a cluster-wide Prometheus server that does Kubernetes SD on Pods, use none to turn off 
      provider: "prometheus"                     # for future extensibility 

  # server parameters
  server:
    users:
      admin:
        username: admin
        password: 5LVTpbGE2cGFtw69
      replication:
        username: repl
        password: 5LVTpbGE2cGFtw69
    storage:
      class: null                                # e.g. high
      size: 256Mi
    replicas: 3
    image: mariadb/server:10.3
    port: 3306
    labels: null                                 # custom labels applied to mariadb server pods only
    annotations: null                            # custom annotations applied to mariadb server pods only
    resources:
      requests:
        cpu: null                                # e.g. "1000m"
        memory: null                             # e.g. "3G"
      limits:
        cpu: null                                # e.g. "3000m"
        memory: null                             # e.g. "9G"
    restore:
      restoreFrom: null                          # name of restore subdirectory
      claimName: null
    monitoring:
      image: prom/mysqld-exporter:v0.11.0

  # maxscale parameters
  maxscale:
    image: mariadb/maxscale:2.2
    labels: null                                 # custom labels applied to maxscale pods only
    annotations: null                            # custom annotations applied to maxscale pods only
    ports:
      readonly: 4008
      readwrite: 4006
    replicas: 2
    resources:
      requests:
        cpu: null     # e.g. "1000m"
        memory: null  # e.g. "3G"
      limits:
        cpu: null     # e.g. "3000m"
        memory: null  # e.g. "9G"
    monitoring:
      image: skord/maxscale_exporter:latest

  # statestore parameters
  statestore:
    image: mariadb/statestore:0.0.3

  # columnstore cluster parameters
  columnstore:
    singlenodeCombined: false
    stableIpServices: false
    image: nastybuff/cs:1.2.3
    numBlocksPct: 1024M
    totalUmMemory: 1G
    pm:
      replicas: 3
      # We want to handle configurations of UM and PM separately
      # resources:
      #   requests:
      #     cpu: null                                # e.g. "1000m"
      #     memory: null                             # e.g. "3G"
      #   limits:
      #     cpu: null                                # e.g. "3000m"
      #     memory: null
    um:
      replicas: 1
      # We want to handle configurations of UM and PM separately 
      # resources:
      #   requests:
      #     cpu: null                                # e.g. "1000m"
      #     memory: null                             # e.g. "3G"
      #   limits:
      #     cpu: null                                # e.g. "3000m"
      #     memory: null
      
    #The following parameters will be removed from the final setup
    test: false
    sandbox: false
    retries: 60 # 60x5=300sec - up to 5min

  # backup parameters
  backup:
    image: gcr.io/dbaas-development/mariadb-operator-python:0.0.5
    schedule: null                            # crontab format like "* * * * *"
    secret: "random_string"
    target:
      type: auto
      server: null
      path: /
