mariadb:
  debug: 

  # general cluster parameters
  cluster:
    id: null                                     # e.g. "1"
    topology: masterslave                        # possible values "masterslave", "standalone", "galera" or "backup" 
                                                 #or "columnstore"
    labels: null                                 # custom labels to be added to the mariadb service, e.g. for discovery   
    annotations: null                            # custom annotations to be added to each pod in the cluster

  # server parameters
  server:
    users:
      admin:
        username: admin
        password: 5LVTpbGE2cGFtw69
      replication:
        username: repl
        password: 5LVTpbGE2cGFtw69
    storage:
      class: null                                # e.g. high
      size: 256Mi
    replicas: 3
    image: mariadb/server:10.3
    port: 3306
    labels: null                                 # custom labels applied to mariadb server pods only
    annotations: null                            # custom annotations applied to mariadb server pods only
    resources:
      requests:
        cpu: null                                # e.g. "1000m"
        memory: null                             # e.g. "3G"
      limits:
        cpu: null                                # e.g. "3000m"
        memory: null                             # e.g. "9G"
    backup:
      nfs:
        server: null                             # NFS server hostname or ip
        path: /                                  # NFS path to mount
      restoreFrom: null                          # name of restore subdirectory

# maxscale parameters
  maxscale:
    image: mariadb/maxscale:2.2
    labels: null                                 # custom labels applied to maxscale pods only
    annotations: null                            # custom annotations applied to maxscale pods only
    ports:
      readonly: 4008
      readwrite: 4006
    replicas: 2
    resources:
      requests:
        cpu: null     # e.g. "1000m"
        memory: null  # e.g. "3G"
      limits:
        cpu: null     # e.g. "3000m"
        memory: null  # e.g. "9G"

# statestore parameters
  statestore:
    image: mariadb/statestore:0.0.3

# columnstore cluster parameters
  columnstore:
    pm:
      moduleName: mdb-cs-pm-module
      replicas: 3
      #postConfigInput: 2\n1\nn\ny\ncolumnstore-1\n1\n # Replication
      postConfigInput: 2\n1\nn\nn\ncolumnstore-1\n1\n  #No Replication
    um:
      moduleName: mdb-cs-um-module
      replicas: 1
    image: nastybuff/cs:latest
    test: true
    sandbox: true
    retries: 60 # 60x5=300sec - up to 5min 
