# Copyright (C) 2018, MariaDB Corporation
#
# Defines a columnstore configuration in a StatefulSet behind
# a headless service. 

# Allows scaling the number of server instances
# by using:
# kubectl scale sts <label>-mdb-clust --replicas=<number of server instances>

# Headless service for stable DNS entries for StatefulSet members
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mdb-clust
  labels:
    mariadb: {{ .Release.Name }}
    entrypoint.mariadb: {{ .Release.Name }}
    {{- if .Values.mariadb.cluster.id }}
    id.mariadb: "{{ .Values.mariadb.cluster.id }}"
    {{- end }}
    {{- if .Values.mariadb.cluster.labels }}
{{ toYaml .Values.mariadb.cluster.labels | indent 4 }}
    {{- end }}
    {{- if .Values.mariadb.server.labels }}
{{ toYaml .Values.mariadb.server.labels | indent 4 }}
    {{- end }}
spec:
  ports:
  - name: mariadb
    port: {{ .Values.mariadb.server.port }}
    targetPort: {{ .Values.mariadb.server.port }}
  clusterIP: None
  selector:
    mariadb: {{ .Release.Name }}
---
{{- $root := . -}}
{{- range $pod_num, $e := until ( .Values.mariadb.columnstore.um.replicas | int) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $root.Release.Name }}-stableip-um-{{ $pod_num}}
spec:
  ports:
    - port: 3306
      name: mariadb
    - port: 22
      name: ssh
  selector:
    statefulset.kubernetes.io/pod-name: {{ $root.Release.Name }}-mdb-cs-um-module-{{$pod_num}}
---
{{- end -}}
{{- range $pod_num, $e := until ( .Values.mariadb.columnstore.pm.replicas |int) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $root.Release.Name }}-stableip-pm-{{ $pod_num}}
spec:
  ports:
    - port: 3306
      name: mariadb
    - port: 22
      name: ssh
  selector:
    statefulset.kubernetes.io/pod-name: {{ $root.Release.Name }}-mdb-cs-pm-module-{{$pod_num}}
---
{{- end -}}
# a StatefulSet for the master/slave cluster
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-mdb-cs-pm-module
  labels:
    mariadb: {{ .Release.Name }}
    {{- if .Values.mariadb.cluster.id }}
    id.mariadb: "{{ .Values.mariadb.cluster.id }}"
    {{- end }}
    {{- if .Values.mariadb.cluster.labels }}
{{ toYaml .Values.mariadb.cluster.labels | indent 4 }}
    {{- end }}
    {{- if .Values.mariadb.server.labels }}
{{ toYaml .Values.mariadb.server.labels | indent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      mariadb: {{ .Release.Name }}
  serviceName: {{ .Release.Name }}-mdb-clust
  replicas: {{ .Values.mariadb.columnstore.pm.replicas }}
  template:
    metadata:
      {{- if or (.Values.mariadb.cluster.annotations) (.Values.mariadb.server.annotations) }}
      annotations:
      {{- end }}
      {{- if .Values.mariadb.cluster.annotations }}
{{ toYaml .Values.mariadb.cluster.annotations | indent 8 }}
      {{- end }}
      labels:
        mariadb: {{ .Release.Name }}
        {{- if .Values.mariadb.cluster.id }}
        id.mariadb: {{ .Values.mariadb.cluster.id }}
        {{- end }}
    spec:
      initContainers:
      ## runs an initialization script to prepare the correct startup configuration
      - name: init-columnstore-pm
        image: {{ .Values.mariadb.columnstore.image }}
        command:
          - bash
          - /mnt/config-template/init-configurations.sh
          - columnstore
        env:
          - name: BACKUP_CLAIM_NAME
            value: {{ .Values.mariadb.server.backup.claimName }}
          - name: CLUSTER_TOPOLOGY
            value: {{ .Values.mariadb.cluster.topology }}
          - name: MARIADB_CS_NODE
            value: PM
        volumeMounts:
          - mountPath: /mnt/secrets
            name: mariadb-secrets-vol
            readOnly: true
          - mountPath: /docker-entrypoint-initdb.d
            name: mariadb-entrypoint-vol
          - mountPath: /mnt/config-template
            name: mariadb-configtemplate-vol
          - mountPath: /mnt/config-map
            name: mariadb-config-vol
      containers:
#Columnstore Module
      - name: columnstore-module-pm
        image: {{ .Values.mariadb.columnstore.image }}
        # start a mariadb instance
        command:
        - bash
        - /mnt/config-map/start-mariadb-instance.sh
        # command: ["ls"]
        # args: ["mnt/config-map"]
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "Y"
        - name: CLUSTER_TOPOLOGY
          value: {{ .Values.mariadb.cluster.topology }}
        - name: MARIADB_CS_NODE
          value: PM
        ports:
        - containerPort: 3306
        {{- if or (.Values.mariadb.server.resources.limits.cpu) (.Values.mariadb.server.resources.limits.memory) (.Values.mariadb.server.resources.requests.cpu) (.Values.mariadb.server.resources.requests.memory) }}
        resources:
        {{- end }}
          {{- if or (.Values.mariadb.server.resources.requests.cpu) (.Values.mariadb.server.resources.requests.memory) }}
          requests:
          {{- end }}
            {{- if .Values.mariadb.server.resources.requests.cpu }}
            cpu: {{ .Values.mariadb.server.resources.requests.cpu }}
            {{- end }}
            {{- if .Values.mariadb.server.resources.requests.memory }}
            memory: {{ .Values.mariadb.server.resources.requests.memory }}
            {{- end }}
          {{- if or (.Values.mariadb.server.resources.limits.cpu) (.Values.mariadb.server.resources.limits.memory) }}
          limits:
          {{- end }}
            {{- if .Values.mariadb.server.resources.limits.cpu }}
            cpu: {{ .Values.mariadb.server.resources.limits.cpu }}
            {{- end }}
            {{- if .Values.mariadb.server.resources.limits.memory }}
            memory: {{ .Values.mariadb.server.resources.limits.memory }}
            {{- end }}
        volumeMounts:
        {{- if .Values.mariadb.server.backup.claimName }}
        - name: backup-data-storage
          mountPath: /backup
        {{- end }}
        - name: mariadb-entrypoint-vol
          mountPath: /docker-entrypoint-initdb.d
        - name: mariadb-config-vol
          mountPath: /mnt/config-map
        # a permanent volume for data storage
        - name: data
          mountPath: /usr/local/mariadb/columnstore/mysql/db
          subPath: db
        # livenessProbe:
        #   exec:
        #     command:
        #     - bash
        #     - /mnt/config-map/liveness.sh
        #   initialDelaySeconds: 15
        #   periodSeconds: 10
        #   timeoutSeconds: 5
        # readinessProbe:
        #   exec:
        #     command:
        #     - bash
        #     - /mnt/config-map/liveness.sh
        #   initialDelaySeconds: 15
        #   periodSeconds: 2
        #   timeoutSeconds: 1
      volumes:
      {{- if .Values.mariadb.server.backup.claimName }}
      - name: backup-data-storage
        persistentVolumeClaim:
          claimName: {{ .Values.mariadb.server.backup.claimName }}
      {{- end }}
      - name: mariadb-entrypoint-vol
        emptyDir: {}
      - name: mariadb-config-vol
        emptyDir: {}
      - name: mariadb-configtemplate-vol
        configMap:
          name: {{ .Release.Name }}-mariadb-config
      - name: mariadb-secrets-vol
        secret:
          secretName: {{ .Release.Name }}-mariadb-secret

  # ensures persistent volumes end up on the same pod
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        mariadb: {{ .Release.Name }}
        storage.mariadb: {{ .Release.Name }}
        {{- if .Values.mariadb.cluster.id }}
        id.mariadb: "{{ .Values.mariadb.cluster.id }}"
        {{- end }}
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.mariadb.server.storage.size }}
      {{- if .Values.mariadb.server.storage.class }}
      storageClassName: {{ .Values.mariadb.server.storage.class }}
      {{- end }}

---

# a StatefulSet for the columnstore UMs cluster
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-mdb-cs-um-module
  labels:
    mariadb: {{ .Release.Name }}
    columnstore.um.mariadb: {{ .Release.Name }}
    {{- if .Values.mariadb.cluster.id }}
    id.mariadb: "{{ .Values.mariadb.cluster.id }}"
    {{- end }}
    {{- if .Values.mariadb.cluster.labels }}
{{ toYaml .Values.mariadb.cluster.labels | indent 4 }}
    {{- end }}
    {{- if .Values.mariadb.server.labels }}
{{ toYaml .Values.mariadb.server.labels | indent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      mariadb: {{ .Release.Name }}
      columnstore.um.mariadb: {{ .Release.Name }}
  serviceName: {{ .Release.Name }}-mdb-clust
  replicas: {{ .Values.mariadb.columnstore.um.replicas }}
  template:
    metadata:
      {{- if or (.Values.mariadb.cluster.annotations) (.Values.mariadb.server.annotations) }}
      annotations:
      {{- end }}
      {{- if .Values.mariadb.cluster.annotations }}
{{ toYaml .Values.mariadb.cluster.annotations | indent 8 }}
      {{- end }}
      labels:
        mariadb: {{ .Release.Name }}
        columnstore.um.mariadb: {{ .Release.Name }}
        {{- if .Values.mariadb.cluster.id }}
        id.mariadb: {{ .Values.mariadb.cluster.id }}
        {{- end }}
    spec:
      initContainers:
      ## runs a state store client to determine the IP of the active master
      - name: init-get-um-master
        image: {{ .Values.mariadb.statestore.image }}
        command: ["/bin/sh"]
        args: ["-c", "cd /root; node ./client.js mariadb-init {{ .Release.Name }}-mdb-state /mnt/config-map"]
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /mnt/config-map
            name: mariadb-config-vol
          - mountPath: /mnt/config-template
            name: mariadb-configtemplate-vol
      ## runs an initialization script to prepare the correct startup configuration
      - name: init-columnstore-um
        image: {{ .Values.mariadb.columnstore.image }}
        command:
          - bash
          - /mnt/config-template/init-configurations.sh
          - columnstore
        env:
          - name: BACKUP_CLAIM_NAME
            value: {{ .Values.mariadb.server.backup.claimName }}
          - name: CLUSTER_TOPOLOGY
            value: {{ .Values.mariadb.cluster.topology }}
          - name: MARIADB_CS_NODE
            value: UM
        volumeMounts:
          - mountPath: /mnt/secrets
            name: mariadb-secrets-vol
            readOnly: true
          - mountPath: /docker-entrypoint-initdb.d
            name: mariadb-entrypoint-vol
          - mountPath: /mnt/config-template
            name: mariadb-configtemplate-vol
          - mountPath: /mnt/config-map
            name: mariadb-config-vol
      containers:
#Columnstore Module
      - name: columnstore-module-um
        image: {{ .Values.mariadb.columnstore.image }}
        # start a mariadb instance
        command:
        - bash
        - /mnt/config-map/start-mariadb-instance.sh
        # command: ["ls"]
        # args: ["mnt/config-map"]
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "Y"
        - name: CLUSTER_TOPOLOGY
          value: {{ .Values.mariadb.cluster.topology }}
        - name: MARIADB_CS_NODE
          value: UM
        ports:
        - containerPort: 3306
        {{- if or (.Values.mariadb.server.resources.limits.cpu) (.Values.mariadb.server.resources.limits.memory) (.Values.mariadb.server.resources.requests.cpu) (.Values.mariadb.server.resources.requests.memory) }}
        resources:
        {{- end }}
          {{- if or (.Values.mariadb.server.resources.requests.cpu) (.Values.mariadb.server.resources.requests.memory) }}
          requests:
          {{- end }}
            {{- if .Values.mariadb.server.resources.requests.cpu }}
            cpu: {{ .Values.mariadb.server.resources.requests.cpu }}
            {{- end }}
            {{- if .Values.mariadb.server.resources.requests.memory }}
            memory: {{ .Values.mariadb.server.resources.requests.memory }}
            {{- end }}
          {{- if or (.Values.mariadb.server.resources.limits.cpu) (.Values.mariadb.server.resources.limits.memory) }}
          limits:
          {{- end }}
            {{- if .Values.mariadb.server.resources.limits.cpu }}
            cpu: {{ .Values.mariadb.server.resources.limits.cpu }}
            {{- end }}
            {{- if .Values.mariadb.server.resources.limits.memory }}
            memory: {{ .Values.mariadb.server.resources.limits.memory }}
            {{- end }}
        volumeMounts:
        {{- if .Values.mariadb.server.backup.claimName }}
        - name: backup-data-storage
          mountPath: /backup
        {{- end }}
        - name: mariadb-entrypoint-vol
          mountPath: /docker-entrypoint-initdb.d
        - name: mariadb-config-vol
          mountPath: /mnt/config-map
        # a permanent volume for data storage
        - name: data
          mountPath: /usr/local/mariadb/columnstore/mysql/db
          subPath: db
        # livenessProbe:
        #   exec:
        #     command: ["mysqladmin", "ping"]
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        #   timeoutSeconds: 5
        # readinessProbe:
        #   exec:
        #     # Check we can execute queries over TCP (skip-networking is off).
        #     command: ["mysql", "-h", "127.0.0.1", "-e", "SELECT 1"]
        #   initialDelaySeconds: 5
        #   periodSeconds: 2
        #   timeoutSeconds: 1

      # runs a state store client to ensure the state is being maitained
      - name: state-client
        image: {{ .Values.mariadb.statestore.image }}
        command: ["/bin/sh"]
        args: ["-c", "cd /root; node ./client.js mariadb {{ .Release.Name }}-mdb-state /mnt/config-map"]
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /mnt/config-template
            name: mariadb-configtemplate-vol
      restartPolicy: Always
      volumes:
      {{- if .Values.mariadb.server.backup.claimName }}
      - name: backup-data-storage
        persistentVolumeClaim:
          claimName: {{ .Values.mariadb.server.backup.claimName }}
      {{- end }}
      - name: mariadb-entrypoint-vol
        emptyDir: {}
      - name: mariadb-config-vol
        emptyDir: {}
      - name: mariadb-configtemplate-vol
        configMap:
          name: {{ .Release.Name }}-mariadb-config
      - name: mariadb-secrets-vol
        secret:
          secretName: {{ .Release.Name }}-mariadb-secret

  # ensures persistent volumes end up on the same pod
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        mariadb: {{ .Release.Name }}
        storage.mariadb: {{ .Release.Name }}
        {{- if .Values.mariadb.cluster.id }}
        id.mariadb: "{{ .Values.mariadb.cluster.id }}"
        {{- end }}
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.mariadb.server.storage.size }}
      {{- if .Values.mariadb.server.storage.class }}
      storageClassName: {{ .Values.mariadb.server.storage.class }}
      {{- end }}